[2024-09-16T04:06:44.104+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: P2M3_student_DAG_hck.load_csv_to_postgres manual__2024-09-16T04:06:19.843578+00:00 [queued]>
[2024-09-16T04:06:44.120+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: P2M3_student_DAG_hck.load_csv_to_postgres manual__2024-09-16T04:06:19.843578+00:00 [queued]>
[2024-09-16T04:06:44.121+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-09-16T04:06:44.155+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): load_csv_to_postgres> on 2024-09-16 04:06:19.843578+00:00
[2024-09-16T04:06:44.167+0000] {standard_task_runner.py:60} INFO - Started process 235 to run task
[2024-09-16T04:06:44.189+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'P2M3_student_DAG_hck', 'load_csv_to_postgres', 'manual__2024-09-16T04:06:19.843578+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_Intan_DAG.py', '--cfg-path', '/tmp/tmp39t0y499']
[2024-09-16T04:06:44.194+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask load_csv_to_postgres
[2024-09-16T04:06:44.302+0000] {task_command.py:423} INFO - Running <TaskInstance: P2M3_student_DAG_hck.load_csv_to_postgres manual__2024-09-16T04:06:19.843578+00:00 [running]> on host b43b870320b1
[2024-09-16T04:06:44.505+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hck' AIRFLOW_CTX_DAG_ID='P2M3_student_DAG_hck' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T04:06:19.843578+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-16T04:06:19.843578+00:00'
[2024-09-16T04:06:44.525+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_Intan_DAG.py", line 24, in load_csv_to_postgres
    df = pd.read_csv('D:\Bootcamp Intan\Phase2\melb_data.csv')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Bootcamp Intan\\Phase2\\melb_data.csv'
[2024-09-16T04:06:44.547+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=P2M3_student_DAG_hck, task_id=load_csv_to_postgres, execution_date=20240916T040619, start_date=20240916T040644, end_date=20240916T040644
[2024-09-16T04:06:44.584+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task load_csv_to_postgres ([Errno 2] No such file or directory: 'D:\\Bootcamp Intan\\Phase2\\melb_data.csv'; 235)
[2024-09-16T04:06:44.604+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-16T04:06:44.661+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
